drive() {
  open /Applications/Brave\ Browser.app/ "https://drive.google.com/drive/search?hl=en&q=$1"
}

export EDITOR="code -w"
export GIT_EDITOR="code -nw"

export GOPATH=$HOME/code/go
export PATH=$PATH:$GOPATH/bin

export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

[ -f ~/.env ] && source ~/.env

. "$HOME/.cargo/env"
