export ZSH="$HOME/.oh-my-zsh"

plugins=(
  git
  bundler
  dotenv
  last-working-dir
  macos
  web-search
  history
  yarn
  extract
  sudo
)

source $ZSH/oh-my-zsh.sh

# Additional PATH entries
PATH=~/.console-ninja/.bin:$PATH

export NARGO_HOME="$HOME/.nargo"
export PATH="$PATH:$NARGO_HOME/bin"

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac

# Antigravity
export PATH="$HOME/.antigravity/antigravity/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"
